#!/usr/bin/env bash
# Write a Bash script that displays:
# script that gives you information about the school file.

i="school"
if [ -e "$i" ]
then
    echo "$i school file exists"
    if [ -s "$i" ]
    then
	echo "$i school file does not empty"
    else
	echo "$i school file is empty"
    fi
    if [ -f "$i" ]
    then
	echo "$i school file is not empty"
    fi
else
    echo "$i school is a regular file"
fi
